---
title: "COVID 19 Report"
author:
- familyname: Zhang
  othernames: Lintian
  address: Monash Universtiy
  email: ltzha1@student.monash.edu
  correspondingauthor: true
  qualifications:  Bachelor of Accounting
- familyname: Widjaya
  othernames: Arthur Andersen
  address: Monash University
  email: awid0001@student,monash.edu
  correnpondingauthor: true
  qualifications: Bachelor of Accounting
- familyname: Wang
  othernames: Hanchen
  address: Monash University
  email: hwan0143@student.monash.edu
  correspondingauthor: true
  qualifications:  Bachelor of Finance
- familyname: Zou
  othernames: Ying
  address: Monash University
  email: yzou0014@student.monash.edu
  correspondingauthor: true
  qualifications: Bachelor of Economics
department: Team Amazing
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
  always_allow_html: true
header-includes:
 \usepackage{float}
 \floatplacement{figure}{H}
 \floatplacement{table}{H}
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(stargazer)
library(PerformanceAnalytics)
library(tidyverse)
library(bookdown)
library(plotly)

```

```{r}

```


# Introduction



\section*{Total cases in Australia}

```{r, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
covid <- read_csv("Data/All.csv")
```

```{r, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
covid_long <- covid %>% 
  mutate(date = as.Date(date, '%d-%b')) %>% 
  pivot_longer(cols = -date,
             names_to = "state",
             values_to = "Count") 
  dates <- unique(sort(covid_long$date)) 
  covid_long$date <- factor(covid_long$date, ordered = T)
```

# Total COVID 19 cases from each state in the last 28 days

```{r table1, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
table <- covid_long %>% 
  group_by(state) %>% 
  summarise(total = sum(Count)) %>% 
  arrange(desc(total))

knitr::kable(table, caption = "Total cases in 28 days") %>% 
kable_classic(full_width = F, html_font = "Cambria")
```


# Highest and lowest COVID 19 cases in Australia 

```{r, fig.width=10, figref1, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
ggplot(covid_long,
       aes(x = reorder(date, -Count),
y = Count, fill = state)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1)) +
expand_limits(x = c(0, NA), y = c(0, NA)) + 
scale_y_continuous(labels = scales::label_number_si())  +xlab("date") + ggtitle("Highest and lowest COVID 19 cases in Australia")

```

# COVID 19 cases in Australia in the last 28 days

```{r, figref2, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
 ggplot(covid_long,
       aes(x = date,
y = Count, fill = state)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1)) +
expand_limits(x = c(0, NA), y = c(0, NA)) + 
scale_y_continuous(labels = scales::label_number_si()) + ggtitle("Daily cases in Australia in the last 28 days")
```


\section*{Recovery}



\section*{Transmission sources of daily cases in Australia}


\section*{Vaccination in Australia}



# Conclusion


